export default[
    {name:'basics',url:'https://youtu.be/atjYxkVWdKE'},
    {name:'technical',url:'https://youtu.be/sogJ7OjLn_Q'},
    {name:'fundamental',url:'https://youtu.be/Lsr9tamExCk'},
    {name:'midieall',url:'https://youtu.be/CQRy11-aQ3M'},
    {name:'mi',url:'https://youtu.be/MivYn3FjRr0'},
    {name:'midibjeall',url:'https://youtu.be/vi3I2KNb2lA'},
    {name:'midieahhll',url:'https://youtu.be/5z5F46CdToM'},
    {name:'midiejjall',url:'https://youtu.be/aoOtqYTXVlo'},
    {name:'midiejnall',url:'https://youtu.be/XTPV9vsQkOI'},
    {name:'midieall',url:'https://youtu.be/EE278o9W25A'},
    {name:'midieall',url:'https://youtu.be/_m-0ndxVgeo'},
    {name:'midieall',url:'https://youtu.be/AsM_rAm3IlQ'},
    {name:'midieall',url:'https://youtu.be/xtPtqQWQNVY'},
    {name:'what is leverage',url:'https://youtu.be/cC4uJA919LY'},
    {name:'equity margin',url:'https://www.youtube.com/watch?v=2j3x0VYnehg'},
    {name:'what is take profit',url:'https://drive.google.com/file/d/1yGQU4wLFm3I9UT1XRRw-0lc1nmJJqyO7/view?usp=sharing'},
    {name:'midieall',url:'https://www.youtube.com/watch?v=2j3x0VYnehg'},
    {name:'midieall',url:'https://www.youtube.com/watch?v=2j3x0VYnehg'},
    {name:'midieall',url:'https://www.youtube.com/watch?v=2j3x0VYnehg'},
    {name:'midieall',url:'https://www.youtube.com/watch?v=2j3x0VYnehg'},
    {name:'midieall',url:'https://www.youtube.com/watch?v=2j3x0VYnehg'},
    {name:'midieall',url:'https://www.youtube.com/watch?v=2j3x0VYnehg'},
    {name:'midieall',url:'https://www.youtube.com/watch?v=2j3x0VYnehg'},
    {name:'midieall',url:'https://www.youtube.com/watch?v=2j3x0VYnehg'},
    {name:'midieall',url:'https://www.youtube.com/watch?v=2j3x0VYnehg'},
    {name:'midieall',url:'https://www.youtube.com/watch?v=2j3x0VYnehg'},
    {name:'midieall',url:'https://www.youtube.com/watch?v=2j3x0VYnehg'},
    {name:'midieall',url:'https://www.youtube.com/watch?v=2j3x0VYnehg'},
    {name:'midieall',url:'https://www.youtube.com/watch?v=2j3x0VYnehg'},
    {name:'midieall',url:'https://www.youtube.com/watch?v=2j3x0VYnehg'},
    {name:'midieall',url:'https://www.youtube.com/watch?v=2j3x0VYnehg'},
    {name:'midieall',url:'https://www.youtube.com/watch?v=2j3x0VYnehg'},
    {name:'midieall',url:'https://www.youtube.com/watch?v=2j3x0VYnehg'},
    {name:'midieall',url:'https://www.youtube.com/watch?v=2j3x0VYnehg'},
    {name:'midieall',url:'https://www.youtube.com/watch?v=2j3x0VYnehg'},
    {name:'midieall',url:'https://www.youtube.com/watch?v=2j3x0VYnehg'},
    {name:'midieall',url:'https://www.youtube.com/watch?v=2j3x0VYnehg'},
    {name:'midieall',url:'https://www.youtube.com/watch?v=2j3x0VYnehg'},
    {name:'midieall',url:'https://www.youtube.com/watch?v=2j3x0VYnehg'},
    {name:'midieall',url:'https://www.youtube.com/watch?v=2j3x0VYnehg'},
   
];